### ISSUE TITLE
Package Control: Skipping file from package named Meteor Autocomplete (TernJS) due to an invalid filename

### ISSUE THREAD

**Issue by krawalli** [Slava/tern-meteor-sublime#3] opened 2015-03-15 07:39 UTC
trying to use this package. Unfortunatly it does not show any completion, but there is nothing in the log/console as useful reason.

On using "update packages" from package control, this shows up:

Package Control: Skipping file from package named Meteor Autocomplete (TernJS) due to an invalid filename

**Comment by Slava** [comment] 2015-03-15 07:40
I cannot reproduce it. What version of Sublime Text do you have? What OS are you running on? What is the invalid file?

And what do you have in your user settings?

**Comment by krawalli** [comment] 2015-03-15 07:53
- build 3065
- Linux (ubuntu)
- i dont know either - there is nothing in the lines around that message

The variable names popup shown in the gif-video while typing: is that because of tern or from another package?

**Comment by Slava** [comment] 2015-03-15 07:57
@krawalli in the gif, you can see that you have types and the completion is based on the return values, not just random tokens in the file.

**Comment by krawalli** [comment] 2015-03-15 08:02
so there is no other package to that like codeIntel - right?

Is there a "debug switch" to get a clue why it does not fire up (even on '.')

[edit]

Ok, seems I've got it running.
Some "project settings" seems to prevent the package to work.

**Comment by Slava** [comment] 2015-03-15 21:14
@krawalli I don't know how to reproduce it. Can you try on a plain Sublime Text w/o any other plugins on a simple meteor project?

**Comment by krawalli** [comment] 2015-03-15 22:41
I will try to.

Maybe its the excluded .meteor folder. Thought this would only affect the display and beeing included from search.

**Comment by raix** [comment] 2015-03-16 07:31
// Not sure if related - just tried to find the package on st3 but wasn't found - mac os

**Comment by Slava** [comment] 2015-03-16 07:33
@raix https://packagecontrol.io/packages/Meteor%20Autocomplete%20%28TernJS%29

**Comment by raix** [comment] 2015-03-16 08:49
![image](https://cloud.githubusercontent.com/assets/1136718/6662947/a2d59042-cbc1-11e4-8640-a18e0f8846c7.png)
Yeah, just don't actually have the "Meteor Autocomplete..." in the package install list?

**Comment by Slava** [comment] 2015-03-16 08:50
No idea. Make sure you have Sublime Text 3 and not 2.

**Comment by raix** [comment] 2015-03-16 08:51
It's 3 (at least the one I installed build 3065) - I'll just check up on it one more time - jic

**Comment by raix** [comment] 2015-03-16 08:53
Odd: 
![image](https://cloud.githubusercontent.com/assets/1136718/6662989/367ab1b0-cbc2-11e4-921c-c40dd86f90ff.png)
I'll see if I can try in a week or so, thank you for the effort!

**Comment by krawalli** [comment] 2015-03-16 09:47
@raix: it does not show up if its already installed

**Comment by Slava** [comment] 2015-05-23 20:19
Closing this due to no way to reproduce :(

If this behavior repeats, let's open a new fresh issue.

**Closed as completed by Slava** 2015-05-23 20:19 UTC
