### ISSUE TITLE
Disable Tern alert?

### ISSUE THREAD

**Issue by peterchoo** [Slava/tern-meteor-sublime#14] opened 2015-04-22 11:34 UTC
Hi there,

I've used your package successfully for a few days, and it's been great. Sometimes, thought, I keep getting this weird issue when I start typing:

![disabletern](https://cloud.githubusercontent.com/assets/5271469/7273300/4446d9b4-e8ea-11e4-9242-1d504e04134d.png)

There was an error in the console, but unfortunately I reinstalled the plugin and now the error isn't there any more.  IIRC the stack trace pointed to here: https://github.com/Slava/tern-meteor-sublime/blob/master/tern.py#L469 saying `KeyError: 'name'`.  Whether that is related to this issue or not I can't say, as the above alert dialog is appearing without that message now.

**Comment by Slava** [comment] 2015-05-23 20:18
Closing as a duplicate of #15. Because of the amount of code ternjs needs to analyze, it just becomes unresponsive.

**Closed as completed by Slava** 2015-05-23 20:18 UTC
