### ISSUE TITLE
Error: EMFILE, too many open files

### ISSUE THREAD

**Issue by frozeman** [Slava/tern-meteor-sublime#17] opened 2015-05-05 06:25 UTC
I just installed it, restarted sublime text and wanting to type and i get (i have multiple windows with project folders of normal sized meteor apps):

```
Failed to start server:

/Users/frozeman/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/node_modules/tern/node_modules/glob/glob.js:115
  var cwd = process.cwd()
                    ^
Error: EMFILE, too many open files
    at new Glob (/Users/frozeman/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/node_modules/tern/node_modules/glob/glob.js:115:21)
    at glob (/Users/frozeman/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/node_modules/tern/node_modules/glob/glob.js:57:11)
    at Function.globSync [as sync] (/Users/frozeman/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/node_modules/tern/node_modules/glob/glob.js:76:10)
    at /Users/frozeman/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/node_modules/tern/bin/tern:262:10
    at Array.forEach (native)
    at startServer (/Users/frozeman/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/node_modules/tern/bin/tern:261:46)
    at Object.<anonymous> (/Users/frozeman/Library/Application Support/Sublime Text 3/Packages/Meteor Autocomplete (TernJS)/node_modules/tern/bin/tern:231:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by Morganjackson** [comment] 2015-05-09 01:09
@frozeman Did you find a fix for this? I get this even on a new meteor project with only one file open.

I tried the suggestions here but no luck: http://stackoverflow.com/questions/8965606/node-and-error-emfile-too-many-open-files

**Comment by frozeman** [comment] 2015-05-09 11:40
Nope. don't know what to do. @Slava any idea?

**Comment by Slava** [comment] 2015-05-23 20:20
Duplicate of #12.

You can google the internet to find way to increase the open files limit on your OS

**Closed as completed by Slava** 2015-05-23 20:20 UTC

**Comment by TrungNghia1908** [comment] 2017-05-09 10:01
https://jaredbarriere.wordpress.com/2016/08/02/sublime-text-3-meteor-auto-complete-ternjs/
This solution work for me.
